#!/usr/bin/env bash
# fast access to mail log exim
# by Action https://github.com/act10
# 14 september 2021

SYSTEM=`uname`
# path to log file
LOG="/var/log/exim4/mainlog"

[ $SYSTEM == "FreeBSD" ] && LOG="/var/log/exim/mainlog"

if [ -z "$1" ]
    then
        echo "Usage maillog textgrep [0-1]"
    else
        if [ -z "$2" ]
            then
                grep $1 $LOG
            else
                if [ $SYSTEM == "FreeBSD" ]
                    then
                        grep -J2 $1 $LOG.$2.bz2
                    else
                        # if Debian Ubuntu Redhat
                        if [ $2 -eq "1" ]
                            then
                                grep $1 $LOG.1
                            else
                                zgrep $1 $LOG.$2.gz
                        fi
                fi
        fi
fi
